project:
  type: website
  output-dir: docs

website:
  title: "Guide to the PTCB Exam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
    background: primary
    search: true

format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    toc: true

editor: visual

